services:
  frontend:
    # build: /client
    image: ronil03/youtube-client:latest
    ports:
      - "5173:5173"
    networks:
      - youtubeurl
  backend:
    # build: /api
    image: ronil03/youtube-api:latest
    ports:
      - "3000:3000"
    networks:
      - youtubeurl
    depends_on:
      - mongodb
  mongodb:
    image: ronil03/mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - youtubeurl
    volumes:
      - mongodb_data:/data/db

networks:
  youtubeurl:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
